### ISSUE TITLE
unexpected type PG::ResultSet#read

### ISSUE THREAD

**Issue by jney** [Crecto/crecto#105]
Hi, Performing a `Repo.insert(user)` i get the following error:

```
PG::ResultSet#read returned a String. A (Int32 | Int64 | Nil) was expected.
```

Despite the record is properly insert into the DB

**Comment by jney** [comment]
my bad, i used id with uuid type, which was not expected by ecto

**Comment by fridgerator** [comment]
you can use a string as a primary key fyi : `field :uuid, String, primary_key: true`
