### ISSUE TITLE
constructor parameters

### ISSUE THREAD

**Issue by jney** [Crecto/crecto#106]
Hi, did i miss something or we can't do

```crystal
u = User.new({attr1: "foo", attr2: "bar", attr3: "baz"})
Repo.insert(u)
```

The only choice is to apply value to each attribute:

```crystal
u = User.new
u.attr1 = "foo"
u.attr2 = "bar"
u.attr3 = "baz"
Repo.insert(u)
```

right?

**Comment by faultyserver** [comment]
By default, that's correct. Crecto implicitly defines the constructors from a [DB::ResultSet](https://github.com/crystal-lang/crystal-db/blob/master/src/db/mapping.cr#L98) and a [Json::PullParser](https://github.com/crystal-lang/crystal/blob/master/src/json/mapping.cr#L83) (via `DB.mapping` and `JSON.mapping`, respectively), as well as a [default, zero-argument constructor](https://github.com/Crecto/crecto/blob/master/src/crecto/model.cr#L56), but that's it.

However, you can easily define your own constructor that accepts arguments to assign the values more cleanly:

```crystal
class User < Crecto::Model
  schema "users" do
    field :name, String
    field :age, Int32
  end

  def initialize(name : String, age : Int32)
    self.name = name
    self.age = age
  end
end

u = User.new("John", 30)
Repo.insert(u)
```

**Comment by fridgerator** [comment]
there is `update_from_hash`

```ruby
user = User.new
user.update_from_hash({"name" => test", "age" => 123})
```

**Comment by jney** [comment]
thanks guys, it is clearer now

**Comment by fridgerator** [comment]
👍
