### ISSUE TITLE
has_many without sole association?

### ISSUE THREAD

**Issue by kirbyfan64** [Crecto/crecto#119]
Right now I have something like:

```crystal
class Role < Crecto::Model
  schema "roles" do
    field :name, String
  end
end


class User < Crecto::Model
  schema "users" do
    field :user, String
    has_many :roles, Role
  end
end
```

This fails to build because of the lack of a foreign key in the *Role* model.

Here's the problem: they should both essentially have multiple ones. By that I mean that each role should be able to have multiple users attached, and each user should be able to have multiple roles attached.

Is this possible with Crecto?

**Comment by kirbyfan64** [comment]
FWIW my workaround right now has been to basically reverse the relationship, and have multiple users per role but only one role per user. It kind of sucks, but it beats nothing I guess. ¯\_(ツ)_/¯

**Comment by fridgerator** [comment]
Ah, are you talking about a many to many relationship?

I haven't tried this yet, I might have time to look into how hard it would be to implement this weekend.

**Comment by kirbyfan64** [comment]
> Ah, are you talking about a many to many relationship?

...apparently? Sorry, I'm still getting used to the relational DB world...

**Comment by fridgerator** [comment]
You could use a join table, and use has many with a through option on both relations.  See the `User`, `Project`, `UserProject` example in the spec helper: https://github.com/Crecto/crecto/blob/master/spec/spec_helper.cr

```crystal
class User < Crecto::Model
  schema "users" do
    field :name
    has_many :user_projects, UserProject, dependent: :destroy
    has_many :projects, through: :user_projects
  end
end

class Project < Crecto::Model
  schema "projects"
    field :name
    has_many :user_projects, UserProject, dependent: :destroy
    has_many :users, through: :user_project
  end
end

class UserProject < Crecto::Model
  schema "user_projects" do
    belongs_to :user, User
    belongs_to :project, Project
  end
end
```

Users will be able to have many projects, and projects will be able to have many users.

Right now its a bit tedious, because the join model has to be created for every record.  But it works!

```crystal
user = User.new
user = Repo.insert(user).instance

project = Project.new
project = Repo.insert(project).instance

user_project = UserProject.new
user_project.user = user
user_project.project = project
Repo.insert(user_project)
```

when you get the user (or project again) it will contain those relations:

```crystal
user = Repo.get(User, user.id, preload: :projects)
user.projects
```

I didn't test any of this code, but thats the point.

**Comment by fridgerator** [comment]
@kirbyfan64 does that work for you?

**Comment by kirbyfan64** [comment]
Thanks for the help!! Out of curiosity, what would the database migration/table creation look like when using `:through`?

**Comment by fridgerator** [comment]
the `UserProject` table would just contain 2 foreign keys, something like:

```sql
CREATE TABLE user_projects(
  user_id INTEGER references users(id),
  project_id INTEGER references projects(id),
  created_at timestamp without time zone,
  updated_at timestamp without time zone
);
```
