### ISSUE TITLE
Changing the method signature of DbLogger to accept Logger

### ISSUE THREAD

**Issue by KevinSjoberg** [Crecto/crecto#138]
Currently, `DBLogger` expects an `IO` object for logging purposes. I'd suggest changing the method signature to accept a `Logger` instance instead. This would also play nicely with [Amber](https://github.com/amberframework/amber).

I'd be happy to submit a PR if you think this is a welcomed change. 🙂

**Comment by grig191** [comment]
@fridgerator added support of Crystal `Logger` in https://github.com/Crecto/crecto/commit/1e9bae0966626777f34d1e5e9d79c457cba45991, but it still doesn't work with amber, so I created PR #140 to fix this.

**Comment by fridgerator** [comment]
closed by #140
