### ISSUE TITLE
Multi delete_all from README not working?

### ISSUE THREAD

**Issue by jwoertink** [Crecto/crecto#146]
If I check the count of my user before running the example in the README, I get 1. After it runs, I still have 1. 
```crystal
    puts Repo.aggregate(User, :count, :id) #=> 1
    multi = Multi.new
    multi.delete_all(User)
    puts Repo.aggregate(User, :count, :id) #=> 1?
```

I did see in the specs that you use `Repo.delete_all`, is that the preferred way to do it? I tried using that, but I get the error related to #145

**Comment by fridgerator** [comment]
multi `delete_all` should definitely work, i'll have to check and test it later

**Comment by jwoertink** [comment]
Cool, thanks!
