### ISSUE TITLE
Question on joins

### ISSUE THREAD

**Issue by jwoertink** [Crecto/crecto#149]
I'm trying to figure out how I would translate this query

```sql
SELECT * FROM users INNER JOIN team_roles ON team_roles.user_id = users.id WHERE team_roles.team_id = 123
```

I started with this

```ruby
Repo.all(User, Query.where(team_id: 123).joins(:team_roles))
```

but I'm not sure how the query would tell `team_id` that it's a column on `team_roles` and not `users`. This actually just blows up with a `Index out of bounds (IndexError)` error.

Then I tried

```ruby
Repo.all(User, Query.where(team_roles: {team_id: 123}).joins(:team_roles))
```

but that gives me a `no overload matches` error.

**Comment by fridgerator** [comment]
how about `Repo.all(User, Query.joins(:team_roles).where("team_roles.team_id = ?", 123))`

**Comment by jwoertink** [comment]
If I use `Query.joins` I get this error:
```text
in src/models/team.cr:22: undefined method 'joins' for Crecto::Repo::Query:Class (did you mean 'join'?)

    q = Query.joins(:team_roles).where("team_roles.team_id = ?", id)
```

If I use `Query.join` I get the `Index out of bounds (IndexError)` error. 😕

**Comment by jwoertink** [comment]
Alright, so it turns out I've been doing a few things wrong, but I think I'm understanding now. I did indeed get this to work, so I'll close it. Thanks for the help! 

On a side note, I'm gonna submit a PR with some updated docs in the README if that's cool.

**Comment by fridgerator** [comment]
Glad you got it working.

Yes please, anything to improve the docs!
