### ISSUE TITLE
How to math with Repo.aggregate value

### ISSUE THREAD

**Issue by ozergul** [Crecto/crecto#157]
Hello

When I want to add 1 to  Repo.aggregate value getting error.. Is it bug?

```crystal
count = Repo.aggregate(User, :count, :id)
puts count + 1
```
Error:
> undefined method '+' for Bool (compile-time type is (Bool | Float32 | Float64 | Int16 | Int32 | Int64 | Int8 | Slice(UInt8) | String | Time | Time::Span | Nil))

**Comment by fridgerator** [comment]
I'm not sure if there is a better way, but you can do `.to_i` or `.to_f` on the result

**Comment by ozergul** [comment]
The problem is the type of variable I think. If I use `Repo.aggregate(User, :count, :id).to_i`, here error:

`undefined method 'to_i' for Bool `

Also I have 335 records in database and can see that number as a result. But can not sum..

**Comment by fridgerator** [comment]
try `Repo.aggregate(User, :count, :id).as(Int32)`

I should look into returning only a number from these methods

**Comment by ozergul** [comment]
Again gives error: 
> (Repo.aggregate(User, :count, :id)).as(Int32) # => cast from Int64 to Int32 failed

Really interesting, for 24 hours I have been fighting with this issue.

**Comment by fridgerator** [comment]
this one ? `Repo.aggregate(User, :count, :id).as(Int64)`

**Comment by fridgerator** [comment]
So it looks like the `aggregate` methods are just returning the result of the `scalar` method from crystal-db, I have a fix for ensuring these methods always return a Number.  So `to_i` and `to_f` are possible.

**Comment by ozergul** [comment]
Thanks worked, so I have an issue I think it is related with type of variables.

```crystal
changeset = Repo.insert(new_user)
if changeset.valid? == false
  puts "Changeset is invalid"
else
  puts "\nThe item was successfully ADDED. ID:#{changeset.instance.id}\n"
  #Here-----> env.session.int("user_id", changeset.instance.id)
  resp(env, {"message": "Success.", "state": true})
end
```
`changeset.instance.id `gives inserted ID there is no problem with it.

But if I want to save it as session value getting this error:
 
```
  no overload matches 'Kemal::Session#int' with types String, (Int32 | Int64 | String | Nil)
Overloads are:
 - Kemal::Session#int(k : String, v : Int32)
 - Kemal::Session#int(k : String)
Couldn't find overloads for these types:
 - Kemal::Session#int(String, Int64)
 - Kemal::Session#int(String, String)
 - Kemal::Session#int(String, Nil)

      env.session.int("user_id", changeset.instance.id)
                  ^~~

```

If I change like this: `changeset.instance.id.as(Int32)` at this time too getting this error:

> Exception: cast from Int64 to Int32 failed, at .... (TypeCastError)

My main problem was [this](https://github.com/kemalcr/kemal-session/issues/65).

**Comment by fridgerator** [comment]
In this case, you might have to store it as a string value then: `changeset.instance.id.to_s`.  Primary keys are interally cast to [`PkeyValue`](https://github.com/Crecto/crecto/blob/master/src/types.cr#L8)

**Comment by ozergul** [comment]
Not working like as(String) ..

**Comment by fridgerator** [comment]
`to_s` should work

**Comment by ozergul** [comment]
Here are error I gave:

```
      pp env.session.int("user_id", changeset.instance.id.to_s)
      ^

in macro 'pp' /usr/local/Cellar/crystal-lang/0.24.2_1/src/macros.cr:95, line 5:

   1.   
   2.     
   3.     __temp_1445 = "#{"env.session.int(\"user_id\", changeset.instance.id.to_s)"} # => "
   4.     ::print __temp_1445
>  5.     __temp_1446 = env.session.int("user_id", changeset.instance.id.to_s)
   6.     PrettyPrint.format(__temp_1446, STDOUT, width: 80 - __temp_1445.size, indent: __temp_1445.size)
   7.     ::puts
   8.     __temp_1446
   9.   

no overload matches 'Kemal::Session#int' with types String, String
Overloads are:
 - Kemal::Session#int(k : String, v : Int32)
 - Kemal::Session#int(k : String)
```

**Comment by fridgerator** [comment]
since you're using `to_s`, you'll have to use `env.session.string` instead of `env.session.int`

**Comment by ozergul** [comment]
Sorry my bad :) Really thanks for your helps and this library.

**Comment by fridgerator** [comment]
👍
