### ISSUE TITLE
"Insert failed" message on schema with no primary key

### ISSUE THREAD

**Issue by reiswindy** [Crecto/crecto#161]
Maybe I'm missing something, but this has been happening when using the MySQL adapter
I have the following model
```crystal
  class UserFollowing < Crecto::Model
    set_created_at_field nil
    set_updated_at_field nil
  
    schema "user_following", primary_key: false do
      belongs_to :follower_user, User, foreign_key: :follower_user_id
      belongs_to :followed_user, User, foreign_key: :followed_user_id
    end
  end
```
Whenever I insert a new UserFollowing object, the object is inserted correctly, but the changeset always gets populated with `[{:field => "insert_error", :message => "Insert Failed"}]`.
```
following = UserFollowing.new
following.follower_user_id = user.id
following.followed_user_id = target_user.id

changeset = MainRepository.insert(following) 
```
Is this intended behaviour?

**Comment by fridgerator** [comment]
Do the mysql logs give more useful information?

**Comment by reiswindy** [comment]
The log showed no errors.
The last executed query was `INSERT INTO user_following (follower_user_id, followed_user_id) VALUES ('4', '1')` which worked correctly.

I think the problem could be because the insert method from the mysql_adapter is returning nil when there's no primary key.
https://github.com/Crecto/crecto/blob/d366d6b244bcb1c2ca25e3956075c4aa03f7c061/src/crecto/adapters/mysql_adapter.cr#L40-L55

So the validation here will always add that error message
https://github.com/Crecto/crecto/blob/d366d6b244bcb1c2ca25e3956075c4aa03f7c061/src/crecto/repo.cr#L217-L236

**Comment by fridgerator** [comment]
@reiswindy You're right, thanks for that

I was able to replicate and fix the issue in [this](https://github.com/Crecto/crecto/tree/fix_insert_with_no_pkey) branch.  So you can use it for now if you want.

There is a pesky unrelated failing sqlite test though that I need to figure out before I can merge the branch.

**Comment by fridgerator** [comment]
@reiswindy should be fixed in master now 👍

**Comment by reiswindy** [comment]
Awesome! Thanks a lot!
