### ISSUE TITLE
Proposed icon

### ISSUE THREAD

**Issue by faustinoaq** [Crecto/crecto#163]
Hi @fridgerator  here is my icon proposal :smile: 

![bitmap](https://user-images.githubusercontent.com/3067335/40850405-1e923e64-658a-11e8-9830-b38df0bd4d69.png)

WDYT?

PS: I'm not a designer but I really think Crecto needs a icon :sweat_smile: 

Source:  https://gist.github.com/faustinoaq/02954fb501082153a3a56510ed280ca7

**Comment by faustinoaq** [comment]
Maybe just this:

![bitmap](https://user-images.githubusercontent.com/3067335/40850637-cdb48be0-658a-11e8-9d8f-20149178f83e.png)

**Comment by faustinoaq** [comment]
Original icon https://openclipart.org/detail/278003/mineralogist-mineral-collector by @juhele

**Comment by fridgerator** [comment]
Yes crecto needs an icon!

I definitely like the simplicity of the 2nd option compared to the first.

Do these have any license?

**Comment by juhele** [comment]
Hi, Openclipart uses Public Domain license:
https://openclipart.org/share
so no problem :-)

**Comment by fridgerator** [comment]
@faustinoaq I changed the organization icon and will update the read me with the logo along w/ the fixes for 0.25.0.  Thanks!!
