### ISSUE TITLE
Can't change config URI at runtime

### ISSUE THREAD

**Issue by mmKALLL** [Crecto/crecto#167]
Let's say I have the following module:

```crystal
module Repo
  extend Crecto::Repo

  config do |conf|
    conf.adapter = Crecto::Adapters::Mysql
    conf.uri = "mysql://root@localhost:3306/test"
  end
end
```

I am trying to run specs for a health check that tests the DB connection. However, it doesn't seem like I can change this uri at spec runtime to point to a nonexistent DB. For example, this doesn't work:

```crystal
  it "should return bad if no DB is connected" do
    Repo.config do |conf|
      conf.uri = "mysql://root@localhost:12345/nonsense"
    end
    get "/v1/health"
    response.status_code.should eq 200
    response.body.should eq "{\"message\":\"bad\"}"
  end
```

Is there a good way for closing/redirecting the DB connection in runtime (while being able to recover it after the spec is done)? I tried to check Crecto source and specs, but it seems like this is not supported right now?

**Comment by fridgerator** [comment]
Correct changing the URI at runtime isn't supported.

Could you possibly use a different `Repo` module (`BadRepo`) that points to a nonsense database and have a testing route which uses it instead?

**Comment by mmKALLL** [comment]
Thank you for the help! I wasn't sure about the testing route, but after trying some things we settled on the following way:

```crystal
  old_db = Repo.config.crecto_db
  it "should return 500 if no DB is connected" do
    Repo.config.uri = "mysql://root@localhost:12345/nonsense"
    Repo.config.crecto_db = nil # Force reconnect
    get "/v1/health", headers: HEADERS
    response.status_code.should eq 500
    response.body.should eq "{\"message\":\"bad\"}"
  ensure
    new_db = Repo.config.crecto_db
    new_db && new_db.close
    Repo.config.uri = old_uri
    Repo.config.crecto_db = old_db
  end
```

I don't think changing URI on runtime has use-cases aside from this, so closing the issue.
