### ISSUE TITLE
Release a minor version (non patch)

### ISSUE THREAD

**Issue by faustinoaq** [Crecto/crecto#168]
Hi @fridgerator 

I just realize you released 0.8.6 (patch version) to fix crystal v0.25.0 compat issues.

This is an issue on devs using amber v0.7.2 + crystal v0.24.2, because their projects can be updated using `~>` pointing most recent patch version.

Can you delete tag and release v0.8.6 and publish v0.9.0? :sweat_smile: 

Now any dev using `amber new app -m crecto` with amber v0.7.2 + crystal v0.24.2 will get compat issues

**Comment by fridgerator** [comment]
done 👍
