### ISSUE TITLE
Looking for more maintainers / collaborators

### ISSUE THREAD

**Issue by fridgerator** [Crecto/crecto#171]

**Comment by fridgerator** [comment]
Nice, can I ask what the project is?

**Comment by jreinert** [comment]
It's an api for a sort of very generalistic and customizable CMS.

**Comment by faultyserver** [comment]
I don't currently have much time to dedicate to contributing to Crecto, but by the end of the year that should be clearing up and will be looking to working on it a lot more.

I've used Crecto in a few applications now and had a lot of good experiences, but also found a few pain points that I'd like to address when I get the chance.
