### ISSUE TITLE
Grouping wheres and or_wheres in parentheses

### ISSUE THREAD

**Issue by jreinert** [Crecto/crecto#200]
A feature that would allow turning something like:

``` crystal
Query.where(name: "foo").and { |q| q.where(age: 20).or_where(age: 30) }
```
into:

`SELECT * FROM users WHERE name = "foo" AND (age = 20 OR age = 30)`

**Comment by jreinert** [comment]
Not sure about the syntax though. Open for discussion!

**Comment by fridgerator** [comment]
This would be awesome.
