### ISSUE TITLE
Regression on latest Postgres verson

### ISSUE THREAD

**Issue by jreinert** [Crecto/crecto#207]
I get a lot of `source for a multiple-column UPDATE item must be a sub-SELECT or ROW() expression (PQ::PQError)` when i run the specs.

210 examples, 3 failures, 7 errors, 0 pending

**Comment by faultyserver** [comment]
Looks like a solution to this may be to just always use `ROW` expressions for updates? https://www.postgresql.org/message-id/25202.1508858486%40sss.pgh.pa.us

```
The following (odd) construction worked in pgv9.x: "UPDATE my_table SET (my_col) = (some value)". This no longer works in v10.

...

Yeah, IIRC this was an intentional change.  The fact that the previous
coding allowed you to do that was a mistake, because per spec you really
need to supply a row value when you parenthesize the SET column list.
As of v10 it should work to write
UPDATE my_table SET (my_col) = ROW(some value)

...

Now it's expecting a normal
row constructor, which can be one of
	ROW(one_expr)
	ROW(an_expr, another_expr [, ...])
	(an_expr, another_expr [, ...])
```

Or crecto could detect this special single-column update case and only use it then, which feels a _little_ bit better.
