### ISSUE TITLE
Unable to make LEFT JOIN to preload association

### ISSUE THREAD

**Issue by byteg** [Crecto/crecto#216]
I have 2 models: Task and TaskLimit. Task belongs to TaskLimit. But task_limit_id might be Nil, so I need to use LEFT JOIN to preload existing TaskLimit's.
The only way I can do join is this:

`query = query.join(:task_limit).preload(:task_limit)`

But It doesn't select Tasks without TaskLimit.
There is a method in source code of Query class, where I can specify String for my JOIN:

`      def self.join(join_string : String)
        self.new.join(join_string)
      end`

But When I try to use it:

`query.join("LEFT JOIN task_limits ON tasks.task_limit_id = task_limits.id").preload(:task_limit)`

I get an error that the method doesn't exist:

> in tmp/1537794230627_console.cr:2: no overload matches 'Crecto::Repo::Query#join' with type String
> Overloads are:
>  - Crecto::Repo::Query#join(join_associations : Array(Symbol))
>  - Crecto::Repo::Query#join(join_association : Symbol)
> 
> query = query.join("LEFT JOIN task_limits ON tasks.task_limit_id = task_limits.id").preload(:task_limit).where(id: [43, 46])
>

**Comment by fridgerator** [comment]
@byteg You might need to specify `branch: master` in your shard.yml file.  Join strings were recently added here: https://github.com/Crecto/crecto/pull/189 and hasn't been in a release yet.

**Comment by byteg** [comment]
@fridgerator Yes, you're absolutely right, it worked! Thank you!
