### ISSUE TITLE
Has many through issue with foreign key

### ISSUE THREAD

**Issue by repomaa** [Crecto/crecto#223]
I have a model which uses a different field than `id` as primary key and it's not possible to have a has many through relation to this model because in [src/crecto/schema/has_many.cr](https://github.com/Crecto/crecto/blob/master/src/crecto/schema/has_many.cr#L49) `id` is assumed by default. Maybe a third option should be introduced to define the final foreign key.

**Comment by duraki** [comment]
Highly approve this feature to be implemented.

**Comment by jreinert** [comment]
Can someone confirm this is no longer an issue? I haven't got the time atm.
