### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by fridgerator** [Crecto/crecto#233]
I have become extremely busy the last year or so, and I just dont have the time to commit to the Crecto community any more.

Crecto currently doesn't work with the latest crystal version, something between 0.27.1 and 0.27.2 broke.

I am creating this issue to see if there are any interested in helping maintain the project.  If not, then I will inquire about moving it into crystal-community.

**Comment by jreinert** [comment]
I still use crecto in a bunch of projects, so I'm willing to help. I can't be the only maintainer though.

**Comment by wontruefree** [comment]
I am interested in helping but I dont know much about ORMs and I cannot commit to if full time.

**Comment by fridgerator** [comment]
I guess the first step would be to get Crecto working with the latest version of Crystal.  I've looked into this a bit but am not sure what the issue is.

I *think* it broke between Crystal 0.27.1 and 0.27.2, which is strange.

**Comment by fridgerator** [comment]
Crecto is working with the latest crystal

**Comment by fridgerator** [comment]
Yes

**Comment by watzon** [comment]
I'd be happy to help maintain if you're still looking

**Comment by fridgerator** [comment]
@watzon Absolutely.  Honestly I don't do much with this library any more, or Crystal in general.  No hate for Crystal I just don't have time.

I invited you as a maintainer, feel free to do so as you please with the library as I probably won't be available much to review or give feedback.

**Comment by watzon** [comment]
Thanks! I've been doing lots of work on it over the past few days. It'll be good to get this library going again rather than having to build my own from scratch.

**Comment by watzon** [comment]
@fridgerator I'm going to be committing a lot over the next couple days/weeks, but PRs have to be reviewed by you before being merged. Not sure if you want to deal with that or if you want to just give me some extra permissions.

**Comment by fridgerator** [comment]
@watzon I changed you to an "Admin" for all the repos, and as an "Owner" for the organization 👍
