### ISSUE TITLE
New release for Crystal 1.0 ? 

### ISSUE THREAD

**Issue by hutou** [Crecto/crecto#253]
It would be great if a new release including the latest commits could be released soon for Crystal 1.0
Thanks

**Comment by kingsleyh** [comment]
Is this project still being maintained or is it dead now?

**Comment by fridgerator** [comment]
Updated db shards, and tests run on crystal 1.0

**Comment by hutou** [comment]
Hi,
Cannot install `crecto` from a basic `shard.yml` with Crystal 1.0.0 

```
...
dependencies:
  crecto:
    github: crecto/crecto
...
```
Output is:
```
$ shards install 
Resolving dependencies
Fetching https://github.com/crecto/crecto.git
Fetching https://github.com/crystal-lang/crystal-db.git
Unable to satisfy the following requirements:

- `crystal (< 1.0.0)` required by `crecto 0.12.0`
- `crystal (>= 0.35.0, < 2.0.0)` required by `db 0.10.1`
Failed to resolve dependencies, try updating incompatible shards or use --ignore-crystal-version as a workaround if no update is available.
```
It seems `crecto` expects a release < 1.0.0 : Is the file `.crystal-version` the culprit ?
