### ISSUE TITLE
Hangs on a table without an auto incremented id

### ISSUE THREAD

**Issue by russ** [Crecto/crecto#76]
I ran into this by accident. I created a table without an auto incrementing id:
```
CREATE TABLE posts(id int primary key, payload text not null);
```

Then when inserting into it with some basic data:
```
post = Post.new
post.payload = "foobar"
Repo.insert(post)
```

It just sits there without erring out or continuing. Creating a table with the correct fields (serial, created_at, updated_at) works just fine.

**Comment by fridgerator** [comment]
@russ Thanks for the info.

I think there are some bugs in the crystal-pg gem.  It also currently hangs if you have a `UNIQUE` column and you try inserting a duplicate record [crystal-db issue #46](https://github.com/crystal-lang/crystal-db/issues/46).

I will comment there that this is another case where it hangs when an exception should be raised.

**Comment by faultyserver** [comment]
I just hit this same thing from a `NOT NULL` constraint, and seem to recall having the same happen in the past.

Basically, it seems like any error on insertion causes the postgres adapter to hang. I get an immediate failure on MySQL and SQLite3.

**Comment by fridgerator** [comment]
@faultyserver I've run into the same issue. There is an [open issue](https://github.com/crystal-lang/crystal-db/issues/46) in crystal-db repo (its been open for a while)

**Comment by akzhan** [comment]
@russ @fridgerator please try with updated crystal-pg.

**Comment by fridgerator** [comment]
fixed in master branch of crystal-pg
