### ISSUE TITLE
`has_many` shouldn't be nilable

### ISSUE THREAD

**Issue by faultyserver** [Crecto/crecto#80]
Currently, `has_many` defines a nilable array for its association:

```crystal
macro has_many(association_name, klass, **opts)
  property {{association_name.id}} : Array({{klass}})?

  ...
end
```

But this has bitten me a few times when I want to use the association either in views or add/remove entries from the association. For example, say I have a class `User` that has many `Memberships`:

```crystal
class User < Crecto::Model
  schema "users" do
    # defines property memberships : Array(Membership)?
    has_many :memberships, Membership
  end
end
```

Now, if I want to iterate the memberships in a view, I first have to check for nil:

```crystal
user = User.new
# This fails because `memberships` is `Array(Membership) | Nil`
user.memberships.each{ }
# This compiles, but may cause a runtime error if `memberships` hasn't been set.
user.memberships.not_nil!.each{ }

# Even more verbose in ECR, with an added local variable
<%- if memberships = user.memberships -%>
  <%- memberships.each do |m| -%>
    ...
  <%- end -%>
<%- end -%>
```

I propose that `has_many` be non-nilable, and instead provide an empty array as the default value. I messed around with this idea last night and came up with this:

```crystal
macro has_many(association_name, klass, **opts)
  def {{association_name.id}} : Array({{klass}})
    @{{association_name.id}} ||= [] of {{klass}}
  end

  def {{association_name.id}}=(o : Array({{klass}}))
    @{{association_name.id}} = o
  end

  ...
end
```

Which has worked for me thus far, and means I can easily do things like

```crystal
user = User.new
user.memberships << Membership.new
user.memberships.each{ }

# No more nil-check logic in ECR!
<%- user.memberships.each do |m| -%>
  ...
<%- end -%>
```

without having to worry about `memberships` being nil.

I think this makes sense and better follows the general conventions for collection filters (e.g., `Enumerable#select`) of defaulting to an empty array when no elements are found.

I can make a full PR (specs, README, etc.) with this if you think it is a valid change.

**Comment by fridgerator** [comment]
@faultyserver That sounds completely valid to me, feel free to make a PR.  Thanks!

**Comment by faultyserver** [comment]
I'm looking at this more completely now and I'm a little hesitant.

Semantically, I think it will work out, but there could be some confusion between an empty set of association objects because none exist, and an empty set because the association hasn't been preloaded.

For example (assuming the same models from above):

```crystal
# A user with some memberships
user1 = User.new
Repo.insert(user1)
membership1 = Membership.new(user: user1)
membership2 = Membership.new(user: user1)
Repo.insert(membership1)

# A user with no memberships
user2 = User.new
Repo.insert(user2)
```

**Comment by faultyserver** [comment]
My original idea for this was to create a `Crecto::Association` class, but I don't think that's entirely necessary.

Since we're already generating accessors in the `has_many` macro, I think it would be sufficient to just raise an `Association '{{association_name}}' not loaded` error in the getter if the property is nil.

We could also add a parameter to force loading if the association has not yet been loaded, though I'm not sure how useful/desirable that would actually be.

I'll mess around with some of this tonight and add them to the PR to show what I mean.
