### ISSUE TITLE
`Repo.all` with `preload` option doesn't actually preload.

### ISSUE THREAD

**Issue by faultyserver** [Crecto/crecto#82]
While trying to use the association changes from #81, I ended up with a fragment based on the "Preload associations" section from the README:

```crystal
users = Repo.all(User, preload: [:memberships]) 


users.each do |user|
  user.memberships
  # ...
end
```

This compiles, but ends up raising a `Crecto::AssociationNotLoaded` error when I try to access `user.memberships`.

At first I thought it might be something wrong with the changes in that PR, but I wasn't able to see what could cause it, so I started going top down from the call to `Repo.all` and quickly found that [the `**opts` hash with `preload` isn't being used](https://github.com/Crecto/crecto/blob/addabfdaebbfdbcd95858c74f0e747543d76fffb/src/crecto/repo.cr#L27).

To test this, I tried using `Repo.all(User, Query.new.preload(:memberships))`, which correctly pre-loaded the association, so the functionality exists, it's just that `Repo.all` isn't reading the `preload` argument.

I messed around for a bit and came up with this as a solution that solved the issue, but I'm not too confident in it.

```crystal
preloads = query.preloads + opts.fetch(:preload, [] of Symbol)
if preloads.any?
  add_preloads(results, queryable, preloads)
end
```

**Comment by faultyserver** [comment]
Here's a quick test that shows the failure:

```crystal
describe "Repo#all" do
  it "should accept a list of preloads" do
    name = "repo_all_with_preloads"
    user = quick_create_user(name)
    post = Post.new
    post.user = user
    Repo.insert(post)
    Repo.insert(post)

    users = Repo.all(User, Query.where(name: name), preload: [:posts])
    users[0].posts.not_nil!.size.should eq(2)
  end
end
```

Note: The `not_nil!` is there so that this test can be run on the current `master` branch.

**Comment by fridgerator** [comment]
thanks for the feedback and the test!
