### ISSUE TITLE
`Repo.get!` returns `Crecto::Model+` instead of given class

### ISSUE THREAD

**Issue by faultyserver** [Crecto/crecto#84]
I'm using `Repo.get!` to load a `belongs_to` relationship, and expected it to return a restricted type.  Here's a simplified version of the code I have:

```crystal
class User < Crecto::Model
  schema "users" do
    field :name, String
    has_many :memberships, Membership
  end
end

class Membership < Crecto::Model
  schema "memberships" do
    belongs_to :user, User
  end
end

membership = Repo.all(Membership).first
user = Repo.get!(membership, :user)
```

With this, I would assume that `user` would be of the type `User`, but instead is the virtual type `Crecto::Model+`. If I try to read any properties of `user` (such as `name`), I get an error:

```crystal
puts user.name
# ...: undefined method 'name' for Membership (compile-time type is Crecto::Model+)
```

It seems like `get!` (and `get`) should be able to cast the result to the appropriate type using `Model#klass_for_association`

**Comment by faultyserver** [comment]
Also, I just realized I have some changes that were needed to get `belongs_to` associations working properly with `get!` (the join tried to use `foreign_key_for_association` instead of `key_for_association`). I can make a separate PR for that since it's mostly unrelated.

**Comment by faultyserver** [comment]
Okay, after messing around with this for a while, I realize why this isn't already implemented: the associations types are resolved at run-time, but the type information is needed at compile-time.

I think it would be _possible_ to do this if all of the association code was written in macros, but that sounds like a terrible idea and would lead to a pretty fragile API.

With that, I'll go ahead and close this issue. Sorry for the unnecessary notifications :)

**Comment by fridgerator** [comment]
No worries, I appreciate the contributions.

Sorry I haven't been very reactive to PR's / issues, I've been busy lately.
