### ISSUE TITLE
preloading through joins is currently throwing an error

### ISSUE THREAD

**Issue by fridgerator** [Crecto/crecto#93]
seems like its trying to use the foreign key as the type?

`Exception: type "test_plan_id" does not exist (PQ::PQError)` test_plan_id being the foreign key on the join table

* triggered with `Repo.get!` with a preload query
* also happens with `get_association`

**Comment by faultyserver** [comment]
Is there a short code sample behind this? I have something that sounds similar, but I'm not getting any errors:

```crystal
```

**Comment by fridgerator** [comment]
I was using something like: `Repo.get!(Race, id, Query.preload(:users))`

So then I tried `get_association` and it did the same thing.

**Comment by fridgerator** [comment]
there must have been something wrong with my setup, I can't replicate this now with a test database
