### ISSUE TITLE
Nested preloads

### ISSUE THREAD

**Issue by faultyserver** [Crecto/crecto#94]
I have a set of associations that form a many_to_many relationship:

```crystal
schema "races" do
  has_many :memberships, Membership
  has_many :users, User, through: :memberships
end

schema "memberships" do
  belongs_to :user, User
  belongs_to :race, Race
end

schema "users" do
  has_many :memberships, Membership
  has_many :users, User, through: :memberships
end
```

In my views, I often need to get information from both the `Membership` and the `User`/`Race` for each membership. The solution I have currently looks like this:

```crystal
# :users doesn't really do anything useful here, since it doesn't set `race.member.user`
race = Repo.get(Race, 1, preload: [:memberships, :users])

race.memberships.each do |member|
  member.user # => raises `AssociationNotLoaded`
  member.user = Repo.get_association!(member, :user)

  # now, the full content of both `user` and `member` are available.
  member.user.name
end
```

But, this is subject to the N+1 problem, so it's not an ideal solution.

I think it'd be nice to have something similar to [Ecto's nested preloads](https://hexdocs.pm/ecto/Ecto.Query.html#preload/3) but Crystal doesn't have keyword lists like Elixir's, so maybe something like this?

```crystal
# `preload` is an `Array(Symbol | NamedTuple)`.
Repo.get(Race, 1, preload: [:locations, { memberships: [:users] }])

# Could look cleaner on Query.preload
Repo.get(Race, 1, Query.preload(:locations, memberships: [:users])
```

I haven't thought at all about what the implementation would look like, so all of this is speculative of an ideal world. It's also possible that I've just missed something completely :)

**Comment by fridgerator** [comment]
Yeah I've thought about nested preloads also.  Theoretically seems possible, since using the symbol we can get the associated classes 👍

**Comment by jreinert** [comment]
I tested it. It works with the new `preload(Symbol, Query)` method. And it's awesome!

For your current usecase actually just using the following query should be sufficient:

``` crystal
Repo.get(Race, 1, Query.preload(:users))
```

Now let's say there's the following additional model:

``` crystal
schema "horses" do
  belongs_to :user, User
end
```

you should be able to get the users including their horses for a race like this:

``` crystal
Repo.get(Race, 1, Query.preload(:users, Query.preload(:horse)))
```

Maybe you meant something else by users though ;)

**Comment by fridgerator** [comment]
Awesome!

**Comment by fridgerator** [comment]
Yeah, @jreinert I added you as a collaborator so you should be able to close issues and such 👍

**Comment by jreinert** [comment]
Cool :+1:
