### ISSUE TITLE
schema without an ID

### ISSUE THREAD

**Issue by jwoertink** [Crecto/crecto#98]
I didn't see this as an option in the code, or in the docs. 

Some tables might not have an ID or any sort of primary key because they could be used as join tables. It would be nice to have an option to specify (or have it documented if this exists)

```crystal
schema "cars" do
  has_many :car_owners, CarOwner
  has_many :owners, Owner, through: :car_owners
end

# maybe something like this?
schema "car_owners", id: false do
  updated_at_field nil
  created_at_field nil
  belongs_to :car, Car
  belongs_to :owner, Owner
end

schema "owners" do
   has_many :car_owners, CarOwner
   has_many :cars, Car, through: :car_owners
end
```

**Comment by fridgerator** [comment]
Definitely a useful option.

You MIGHT be able to get away with throwing `primary_key: true` on another field in that model as a temporary solution?  Right now its used for loading and deleting associations, but if you're doing this manually it might work.

**Comment by jwoertink** [comment]
Cool. I'll try that out. Thanks!
